version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672" # for apps
      - "15672:15672" # for ui
    environment:
      RABBITMQ_DEFAULT_USER: bse2327
      RABBITMQ_DEFAULT_PASS: hse236