services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   # RabbitMQ default port
      - "15672:15672" # Management UI port
    environment:
      - RABBITMQ_DEFAULT_USER=bse2327
      - RABBITMQ_DEFAULT_PASS=hse236
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  orders-service:
    build:
      context: ./OrdersService
    ports:
      - "5171:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__UserName=bse2327
      - RabbitMQ__Password=hse236
    depends_on:
      - rabbitmq
    volumes:
      - orders_data:/app/data
    

  payments-service:
    build:
      context: ./PaymentsService
    ports:
      - "5261:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__UserName=bse2327
      - RabbitMQ__Password=hse236
      - OrdersService__BaseUrl=http://orders-service
    depends_on:
      - rabbitmq
      - orders-service
    volumes:
      - payments_data:/app/data

volumes:
  rabbitmq_data:
  orders_data:
  payments_data:
