version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   # RabbitMQ default port
      - "15672:15672" # Management UI port
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped
    command: >
      bash -c "
        echo 'Waiting for RabbitMQ to start...' &&
        sleep 10 &&
        rabbitmq-server
      "

  orders-service:
    build:
      context: .
      dockerfile: OrdersService/Dockerfile
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__Port=5672
      - RabbitMQ__UserName=guest
      - RabbitMQ__Password=guest
      - ConnectionStrings__DefaultConnection=Data Source=/app/data/Orders.db
    depends_on:
      - rabbitmq
    volumes:
      - orders_data:/app/data
    restart: unless-stopped

  payments-service:
    build:
      context: .
      dockerfile: PaymentsService/Dockerfile
    ports:
      - "5003:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__Port=5672
      - RabbitMQ__UserName=guest
      - RabbitMQ__Password=guest
      - OrdersService__BaseUrl=http://orders-service
      - ConnectionStrings__DefaultConnection=Data Source=/app/data/payments.db
    depends_on:
      - orders-service
    volumes:
      - payments_data:/app/data
    restart: unless-stopped

volumes:
  rabbitmq_data:
  orders_data:
  payments_data:
